---
version: "2.1"
services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/dsolsman/Docker/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
