---
version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/dsolsman/Docker/nextcloud/appdata:/config
      - /:/data
    ports:
      - 443:443
    restart: unless-stopped
